###########################################
#
#	Copyright (c) 2016 Florian Evaldsson
#
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###########################################

load ../alifia.so

$(info ADD 10.5,21.2=$(aadd 10.5,21.2))
$(info SUB 10.5,21.2=$(asub 10.5,21.2))
$(info MUL 10.5,21.2=$(amul 10.5,21.2))
$(info POW 10.5,21.2=$(apow 10.5,21.2))

$(info OR 105,212=$(aor 105,212))
$(info AND 105,212=$(aand 105,212))
$(info XOR 105,212=$(axor 105,212))
$(info MOD 105,212=$(amod 105,212))

$(info MKCTARGET $(actarget ..,.build/alifia.o))
$(info MKCTARGET $(actarget ..,all))
$(info GETROOT $(agetroot ./.git))
$(info GETABSROOT $(agetabsroot ./.git))

all:
